public enum TokenType {
    INT, FLOAT, STRING, IF, ELSE, WHILE, FOR,
    SWITCH, CASE, DEFAULT, FUNC, PROC,
    RETURN, BREAK, CONTINUE,

    PLUS, MINUS, MULTIPLY, DIVIDE, MODULO,
    AND, OR, NOT,
    GREATER, LESS, GREATER_EQUAL, LESS_EQUAL, EQUAL_EQUAL, NOT_EQUAL,

    ASSIGN,
    LPAREN, RPAREN,
    LBRACE, RBRACE,
    SEMICOLON, COMMA, COLON,

    IDENTIFIER,
    INT_LITERAL,
    FLOAT_LITERAL,
    STRING_LITERAL,

    EOF,
    ERROR
}